image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  environment: production
  script:
    - export HUGO_BASEDIR="${HUGO_BASEDIR:-exampleSite}"
    - cd "$HUGO_BASEDIR"
    - hugo --themesDir ../.. --destination ../public
  artifacts:
    paths:
      - public
  retry:
    max: 2
    when:
      - api_failure
      - runner_system_failure
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
