image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  stage: deploy
  environment: production
  script:
    - hugo
  artifacts:
    paths:
      - public
  retry:
    max: 3
    when:
      - api_failure
      - runner_system_failure
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
